### ISSUE TITLE
BSOD kernel_mode_exception_not_handled

### ISSUE THREAD

**Issue by 3d8kAbdul** [KameronHawk/Kernel-VAD-Injector#2]
I injected the test dll and after [*] Allocated Memory For DLL I got a stable BSOD, Test DLL - removed the gs- and sdl- protection check, additionally changed MultiTheading to MT-. Tested Windows 2004, 21h2 Stability bsod k_mode_excemption

**Comment by 3d8kAbdul** [comment]
Tested in windows 21h2

**Comment by KameronHawk** [comment]
What process are you injecting into? And are you changing the windows respectfully?

**Comment by skullcheat** [comment]
> What process are you injecting into? And are you changing the windows respectfully?
> 
> The discord offsets might be out of date you can check IDA pro for latest offset

its work windows 11 22h2 ?
otherwise can't pay you for making work into window 11 22h2 also work for apex legends 
skullcheat#4047
let me know

**Comment by 3d8kAbdul** [comment]
that is, I have to find the offset for this address? uintptr_t FuncToHook = ((uintptr_t)ModBase + ->0xE0A98<-);

**Comment by 3d8kAbdul** [comment]
I found this, what should I do next? https://imgur.com/a/vz6ieik

**Comment by KameronHawk** [comment]
https://github.com/KameronHawk/Kernel-VAD-Injector/blob/main/Usermode/Memory.cpp#L176

Change all instance of FindWindow with the window name you're searching for, example: "gfx_test" is the class name, you can enter the other windows class name or actual window title bar name. 



I also updated the hook to showcase PresentScene instead of PeekMessageW, it seems discord now has a CFG patch on PeekMessage so can't hook there to my knowledge.



Here's how to find PresentScene address in IDA pro x64 by dragging and dropping DiscordHook64.dll into IDA:

Steps:

1.  Shift + F12 - Opens strings windows
2.  Search for (CTRL+F) "Present"
3. Look for "IDXGISwapChain::Present" and double click it
4. Right click the string and click "Jump to xref to operand"
5. Click on the sub_1800XXXXX function below the string.
6. Look for qword_1800XXXXX(a1, a2, a3), in my case qword_1800E8098 was the function pointer.



https://imgur.com/a/hyrZaQe


I will be closing this now, and no longer responding to issues. This was tested on Windows 2004.
